/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_btdetector2_NativeWrapper */

#ifndef _Included_com_btdetector2_NativeWrapper
#define _Included_com_btdetector2_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_btdetector2_NativeWrapper
 * Method:    is_synch_proc_switch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_btdetector2_NativeWrapper_is_1synch_1proc_1switch
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

// PUSH(rmask) emits this: "PUSH {<rmask>}"
#define PUSH(rmask) (0xe92d0000 | (rmask))
// POP(rmask) emits this: "POP {<rmask>}"
#define POP(rmask)  (0xe8bd0000 | (rmask))
// MOVW(rd,x) emits this: "MOVW rd, #:lower16:x"
#define MOVW(rd,x)  (0xe3000000 | (((x)<<4)&0xf0000) | ((rd)<<12) | ((x)&0xfff))
// MOVT(rd,x) emits this: "MOVT rd, #:upper16:x"
#define MOVT(rd,x)  (0xe3400000 | (((x)>>12)&0xf0000) | ((rd)<<12) | ((x)>>16))
// BLX(rm) emits this: "BLX rm"
#define BLX(rm)     (0xe12fff30 | (rm))

// ------------------------

// The following instruction macros are provided for compatibility with legacy
// architectures. Note that these all hard-code part of the operand 2 immediate
// field. The caller specifies only the 8-bit immediate.

// These fields set the 'rotation' field of an operand 2 immediate. Refer to
// the ARMv7-AR ARM for a description of the possible values for this field.
#define OP2_BYTE0   (0x0 << 8)
#define OP2_BYTE1   (0xc << 8)
#define OP2_BYTE2   (0x8 << 8)
#define OP2_BYTE3   (0x4 << 8)

// MOV(rd,x) emits this: "MOV rd, #(imm)"
//      ... where "imm" is derived from "x", and "x" is an operand 2 immediate
//      encoded in 12 bits. Refer to the ARMv7-AR ARM for a description of the
//      possible values for this field.
#define MOV(rd,x)   (0xe3a00000 | ((x)&0xfff) | ((rd)<<12))

// ORR(rd,x) emits this: "ORR rd, rd, #(imm)"
#define ORR(rd,x)   (0xe3800000 | ((x)&0xfff) | ((rd)<<12) | ((rd)<<16))

// ------------------------

// Register numbers.
unsigned int const  ip = 12;
unsigned int const  lr = 14;
unsigned int const  pc = 15;

// Turn a register number into an ORable mask for PUSH or POP.
#define rmask(r)    (1<<(r))

// Declare the built-in __clear_cache function.
extern void __clear_cache (char*, char*);

// Define a type for our test function, to avoid the nasty C syntax for
// function pointer casts.
typedef void (*test_func_t) (void);

