/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_btdetector_BinaryTranslationDetection */

#ifndef _Included_com_btdetector_BinaryTranslationDetection
#define _Included_com_btdetector_BinaryTranslationDetection
//#ifndef _Included_installapp_BinaryTranslationDetection
//#define _Included_installapp_BinaryTranslationDetection

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_btdetector_BinaryTranslationDetection
 * Method:    is_bt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_btdetector_BinaryTranslationDetection_is_1bt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
